name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:        # allow manual run too

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          echo "Pinging Render app..."
          curl -s -o /dev/null -w "%{http_code}" https://fintech-backend-ui09.onrender.com/health || true
